# Generated by Django 3.2.10 on 2022-02-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220216_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
